#!/bin/sh -ex

MYSQL="mysql --user=root --password=${MYSQL_PASS} --batch"


# Prepare MySQL database
/etc/init.d/mysql start

## FIXME: username/password here is hard-coded into overlay/usr/local/owntracks/m2s/settings.py

$MYSQL --execute "CREATE DATABASE owntracks;"
$MYSQL --execute "CREATE USER 'a' IDENTIFIED BY 'a';"
$MYSQL --execute "GRANT ALL on owntracks.* TO 'a';"


/etc/init.d/mysql stop

# JPM
# CA certificate/ server cert/key is created in firstboot inithook upon start

mkdir -p /etc/mosquitto/owntracks


#                                   _ _   _                         __ 
#   _ __ ___   ___  ___  __ _ _   _(_) |_| |_ ___   ___ ___  _ __  / _|
#  | '_ ` _ \ / _ \/ __|/ _` | | | | | __| __/ _ \ / __/ _ \| '_ \| |_ 
#  | | | | | | (_) \__ \ (_| | |_| | | |_| || (_) | (_| (_) | | | |  _|
#  |_| |_| |_|\___/|___/\__, |\__,_|_|\__|\__\___(_)___\___/|_| |_|_|  
#                          |_|                                         

cat > /etc/mosquitto/mosquitto.conf <<!EOFmosquitto
#(@) mosquitto.conf pre-configured for OwnTracks
#
autosave_interval 1800

connection_messages true
log_dest stderr
log_dest topic
log_dest file /var/log/mosquitto/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_type all
log_type debug
log_timestamp true

password_file /etc/mosquitto/mosquitto.pw
acl_file /etc/mosquitto/mosquitto.acl

persistence true
persistence_location /var/lib/mosquitto/
persistence_file mosquitto.db
persistent_client_expiration 1m

pid_file /var/run/mosquitto.pid

retained_persistence true

# bound to 0.0.0.0
listener 1883

listener 8883
tls_version tlsv1
cafile /etc/mosquitto/owntracks/ca.crt
certfile /etc/mosquitto/owntracks/mqttitude.crt
keyfile /etc/mosquitto/owntracks/mqttitude.key
require_certificate false

# # Example: Bridge to Jane
# connection br-me-to-jane
# bridge_cafile /etc/mosquitto/jane/JANE-MQTTitude-ca.crt
# bridge_tls_version tlsv1
# bridge_insecure false
# address jane.example.org:8883
# cleansession false
# clientid br-john-jane
# start_type automatic
# username john
# password s3cr1t
# notifications false
# try_private true
# topic nexus7 in 2 owntracks/jane/ owntracks/jane/
# topic iphone out 2 owntracks/john/ owntracks/john/

!EOFmosquitto

#                                   _ _   _                       
#   _ __ ___   ___  ___  __ _ _   _(_) |_| |_ ___   _ ____      __
#  | '_ ` _ \ / _ \/ __|/ _` | | | | | __| __/ _ \ | '_ \ \ /\ / /
#  | | | | | | (_) \__ \ (_| | |_| | | |_| || (_) || |_) \ V  V / 
#  |_| |_| |_|\___/|___/\__, |\__,_|_|\__|\__\___(_) .__/ \_/\_/  
#                          |_|                     |_|            

# @@@ Warning: populated at first boot!

cat > /etc/mosquitto/mosquitto.pw <<!EOFmosquittopw
!EOFmosquittopw
chown mosquitto /etc/mosquitto/mosquitto.pw
chmod 600 /etc/mosquitto/mosquitto.pw

#                                   _ _   _                   _ 
#   _ __ ___   ___  ___  __ _ _   _(_) |_| |_ ___   __ _  ___| |
#  | '_ ` _ \ / _ \/ __|/ _` | | | | | __| __/ _ \ / _` |/ __| |
#  | | | | | | (_) \__ \ (_| | |_| | | |_| || (_) | (_| | (__| |
#  |_| |_| |_|\___/|___/\__, |\__,_|_|\__|\__\___(_)__,_|\___|_|
#                          |_|                                  

# @@@ Warning: user populated at first boot is appended to this file

cat > /etc/mosquitto/mosquitto.acl <<!EOFmosquittoacl
# Allow anonymous clients access to this topic
topic write test/#

# Allow possible bridge status notifications to work
pattern write $SYS/broker/connection/%c/state

# Authenticated users
# user jjolie
# topic write owntracks/jjolie/#

!EOFmosquittoacl
chown mosquitto /etc/mosquitto/mosquitto.acl
chmod 600 /etc/mosquitto/mosquitto.acl

#             ____                         __ _       
#   _ __ ___ |___ \ ___    ___ ___  _ __  / _(_) __ _ 
#  | '_ ` _ \  __) / __|  / __/ _ \| '_ \| |_| |/ _` |
#  | | | | | |/ __/\__ \ | (_| (_) | | | |  _| | (_| |
#  |_| |_| |_|_____|___/  \___\___/|_| |_|_| |_|\__, |
#                                               |___/ 


# Create a default configuration for m2s
mkdir -p /usr/local/owntracks/default
cat > /usr/local/owntracks/default/m2s-settings.py <<!EOFm2ssettings
#(@)settings.py

logfile	= '/var/log/mosquitto/m2s.log'		
mqtt_broker = 'localhost'       # default: 'localhost'
mqtt_port = 1883                # default: 1883
mqtt_clientid = 'm2s-backend'   # MUST be set
# mqtt_username = 'jane'
# mqtt_password = 'secret'

# List of topics we should subscribe to
topics = [
        'owntracks/#',
    ]

# optional: if any words in this list are present in a topic
# name, ignore the message

# blocked_topics = [ 'isim', 'jjolie' ]

# Storage
storage_plugin = 'storage.py'
dbname = 'owntracks'
dbuser = 'a'
dbpasswd = 'a'

# data_plugins = None
data_plugins = [
        # dbcolumn=pluginname       path-to-plugin.py
        dict(column='weather',      filename='pl-weather.py'),
        dict(column='revgeo',       filename='pl-revgeo.py'),
]

# The following configuration is made available to plugins through
# the m2s object. A plugin can access
#
#	m2s.cf.replublish_topic   or
#	m2s.cf.name
#	etc.
#
# See pl-republish.py for an example which uses 'republish_topic',
# 'republish_users', 'republish_devices'

plugin_configs = {
	"republish_topic" : "local/loca",
	"republish_users" : [ 'john', ],
	"republish_devices" : [ 'iphone', 'nexus', ],
	"name" : "JP Mens",
}

!EOFm2ssettings
